import Link from "next/link";
import { notFound } from "next/navigation";
import { requireWorkspace } from "@/lib/workspace-view.server";
import { workspaceRepository } from "@/lib/control-plane.server";
import { sui, dateLabel } from "@/lib/workspace-display";
import { suiscanUrl, walrusBlobUrl } from "@/lib/explorer";
import { Panel, StatePill, WorkspaceFrame } from "@/components/workspace/WorkspaceFrame";
export const dynamic = "force-dynamic";
export default async function Decision({ params }: { params: Promise<{ slug: string; intentId: string }> }) {
  const { slug, intentId } = await params; const context = await requireWorkspace(slug); const repository = workspaceRepository();
  const result = await repository.decisionForMember(context.organization.id, context.session.user.id, intentId); if (!result) notFound();
  const intent = result.decision; const agent = await repository.agentForMember(context.organization.id, context.session.user.id, intent.agentId);
  const blocked = intent.state.endsWith("blocked"); const unknown = intent.state === "submission_unknown";
  const reasoning = intent.reasoningJson as { prompt?: string; decision?: string; model?: string };
  return <WorkspaceFrame slug={slug} name={context.organization.name} title={blocked ? "Payment blocked" : intent.state === "confirmed" ? "Payment confirmed" : "Payment request"} description={`${agent?.agent.name ?? "Agent"} / ${dateLabel(intent.receivedAt)}`}>
    <Link href={`/app/workspaces/${slug}/decisions`} className="focus-ring inline-flex min-h-11 items-center text-sm text-[var(--accent)]">Back to activity</Link>
    <Panel title={`${sui(intent.amountMist)} SUI`}><div className="flex flex-wrap items-center justify-between gap-4"><span className="break-all font-mono text-sm">To {intent.recipient}</span><StatePill value={intent.state} /></div><p className="mt-4 text-sm leading-6">{unknown ? "The chain outcome is not confirmed yet. Do not retry this payment; Praxis is checking its status." : blocked ? `Stopped before a transfer. ${intent.abortReason?.replaceAll("_", " ") ?? "Policy or simulation checks did not pass."}` : intent.state === "confirmed" ? "The payment was confirmed on Sui." : "This request has not been confirmed as a payment."}</p></Panel>
    <Panel title="Why the agent requested this"><p className="whitespace-pre-wrap break-words text-sm leading-7">{reasoning.decision ?? "No decision explanation was provided."}</p>{reasoning.prompt ? <details className="mt-4"><summary className="focus-ring cursor-pointer text-sm text-[var(--text-mid)]">Original instruction</summary><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-6">{reasoning.prompt}</p></details> : null}</Panel>
    <Panel title="Checks and evidence"><dl className="grid gap-4 text-sm sm:grid-cols-3"><div><dt className="text-[var(--text-low)]">Risk score</dt><dd className="mt-1">{intent.riskScore ?? "Not evaluated"}</dd></div><div><dt className="text-[var(--text-low)]">Evidence</dt><dd className="mt-1">{intent.evidenceState}</dd></div><div><dt className="text-[var(--text-low)]">Pending budget</dt><dd className="mt-1">{result.reservation?.state === "active" ? `${sui(result.reservation.amountMist)} SUI` : "None"}</dd></div></dl><div className="mt-5 flex flex-wrap gap-3">{intent.evidenceBlobId ? <a href={walrusBlobUrl(intent.evidenceBlobId)} target="_blank" rel="noreferrer" className="focus-ring inline-flex min-h-11 items-center rounded border border-[var(--border)] px-4 text-sm">View public evidence</a> : null}{intent.txDigest ? <a href={suiscanUrl("tx", intent.txDigest)} target="_blank" rel="noreferrer" className="focus-ring inline-flex min-h-11 items-center rounded border border-[var(--border)] px-4 text-sm">View Sui transaction</a> : null}</div></Panel>
    <details className="rounded-xl border border-[var(--border)] p-5"><summary className="focus-ring cursor-pointer text-sm text-[var(--text-mid)]">Technical details</summary><pre className="mt-4 max-h-[32rem] overflow-auto whitespace-pre-wrap break-all text-xs leading-6">{JSON.stringify({ intentId: intent.id, purposeTag: intent.purposeTag, idempotencyKey: intent.idempotencyKey, stateVersion: intent.stateVersion, attempts: intent.attemptCount, failureCode: intent.failureCode, evidenceHash: intent.evidenceHash, receiptId: intent.receiptId, policy: intent.policySnapshotJson, simulation: intent.simulationJson, received: intent.receivedAt, simulated: intent.simulatedAt, submitted: intent.submittedAt, completed: intent.completedAt }, null, 2)}</pre></details>
  </WorkspaceFrame>;
}
