import Link from "next/link";
import { notFound } from "next/navigation";
import { AlertTriangle, CheckCircle2, ExternalLink, ShieldCheck } from "lucide-react";
import { requireWorkspace } from "@/lib/workspace-view.server";
import { workspaceRepository } from "@/lib/control-plane.server";
import { suiscanUrl, walrusBlobUrl } from "@/lib/explorer";
import { Panel, StatePill, WorkspaceFrame } from "@/components/workspace/WorkspaceFrame";

export const dynamic = "force-dynamic";
export default async function DecisionDetailPage({ params }: { params: Promise<{ slug: string; intentId: string }> }) {
  const { slug, intentId } = await params; const context = await requireWorkspace(slug); const result = await workspaceRepository().decisionForMember(context.organization.id, context.session.user.id, intentId); if (!result) notFound(); const intent = result.decision; const blocked = intent.state === "blocked" || intent.state.endsWith("_blocked"); const unknown = intent.state === "submission_unknown";
  return <WorkspaceFrame slug={slug} name={context.organization.name} eyebrow="Decision proof" title={blocked ? "Protected spend" : `Intent ${intent.id.slice(0, 8)}`} description={blocked ? "Policy or simulation stopped this request before value transfer. Evidence and on-chain abort recording are reported independently." : unknown ? "The submission result is uncertain. Reconciliation owns the next action; this intent is not safe to retry." : "End-to-end policy, simulation, evidence, and chain state for one hosted request."}>
    <div className={`rounded-[var(--r-md)] border p-4 ${unknown ? "border-[var(--risk-medium)]/40 bg-[var(--risk-medium-tint)]" : blocked ? "border-[var(--risk-low)]/35 bg-[var(--risk-low-tint)]" : "border-[var(--divider)] bg-[var(--surface)]"}`}><div className="flex flex-wrap items-center gap-3">{unknown ? <AlertTriangle className="h-5 w-5 text-[var(--risk-medium)]" /> : blocked ? <ShieldCheck className="h-5 w-5 text-[var(--risk-low)]" /> : <CheckCircle2 className="h-5 w-5 text-[var(--text-mid)]" />}<StatePill value={intent.state} /><span className="text-[12px] text-[var(--text-mid)]">Recovery: {recovery(intent.state, intent.txDigest)}</span></div></div>
    <div className="grid gap-5 lg:grid-cols-2"><Panel title="Request"><dl className="grid gap-3"><Row label="Intent ID" value={intent.id} /><Row label="Recipient" value={intent.recipient} /><Row label="Amount" value={`${intent.amountMist} MIST`} /><Row label="Coin" value={intent.coinType} /><Row label="Purpose tag" value={intent.purposeTag} /><Row label="Idempotency key" value={intent.idempotencyKey} /><Row label="Received" value={intent.receivedAt.toISOString()} /></dl></Panel><Panel title="Operational state"><dl className="grid gap-3"><Row label="Evidence" value={intent.evidenceState} /><Row label="Recommendation" value={intent.recommendation ?? "not available"} /><Row label="Risk score" value={intent.riskScore === null ? "not available" : String(intent.riskScore)} /><Row label="Reservation" value={result.reservation ? `${result.reservation.state}, ${result.reservation.amountMist} MIST` : "none"} /><Row label="Abort reason" value={intent.abortReason ?? "none"} /><Row label="Failure code" value={intent.failureCode ?? "none"} /></dl></Panel></div>
    <Panel title="State timeline" detail="Stored timestamps and state version, not a reconstructed success animation."><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Step label="Received" value={intent.receivedAt} /><Step label="Simulated" value={intent.simulatedAt} /><Step label="Submitted" value={intent.submittedAt} /><Step label="Completed" value={intent.completedAt} /></div><p className="mt-4 font-mono text-[10px] text-[var(--text-low)]">state version {intent.stateVersion} / attempts {intent.attemptCount} / evidence attempts {intent.evidenceAttempts}</p></Panel>
    <div className="grid gap-5 xl:grid-cols-2"><JsonPanel title="Policy snapshots" value={{ walletPolicyVersionId: intent.walletPolicyVersionId, walletPolicyHash: intent.walletPolicyHash, assignmentPolicyVersionId: intent.assignmentPolicyVersionId, assignmentPolicyHash: intent.assignmentPolicyHash, effectivePolicyHash: intent.effectivePolicyHash, policy: intent.policySnapshotJson }} /><JsonPanel title="Simulation" value={intent.simulationJson ?? { status: "not available", simulationHash: intent.simulationHash }} /></div>
    <Panel title="Verified evidence and chain references"><div className="grid gap-3">{intent.evidenceBlobId ? <a className="focus-ring inline-flex min-h-11 min-w-0 items-center gap-2 break-all rounded border border-[var(--border-hi)] px-3 font-mono text-[11px] hover:text-[var(--accent)]" href={walrusBlobUrl(intent.evidenceBlobId)} target="_blank" rel="noreferrer">Walrus {intent.evidenceBlobId}<ExternalLink className="h-4 w-4 shrink-0" /></a> : <p className="text-[12px] text-[var(--text-low)]">No published evidence blob. {intent.evidenceLastError ? `Publisher status: ${intent.evidenceLastError}` : "Publication has not completed."}</p>}{intent.evidenceHash ? <Row label="Evidence hash" value={intent.evidenceHash} /> : null}{intent.txDigest ? <Link className="focus-ring inline-flex min-h-11 min-w-0 items-center gap-2 break-all rounded border border-[var(--border-hi)] px-3 font-mono text-[11px] hover:text-[var(--accent)]" href={suiscanUrl("tx", intent.txDigest)} target="_blank" rel="noreferrer">Sui transaction {intent.txDigest}<ExternalLink className="h-4 w-4 shrink-0" /></Link> : <p className="text-[12px] text-[var(--text-low)]">No Sui transaction digest stored.</p>}{intent.receiptId ? <Row label="Receipt object" value={intent.receiptId} /> : null}</div></Panel>
  </WorkspaceFrame>;
}
function Row({ label, value }: { label: string; value: string }) { return <div className="min-w-0 border-b border-[var(--divider)] pb-2"><dt className="text-[10px] uppercase tracking-[0.08em] text-[var(--text-low)]">{label}</dt><dd className="mt-1 break-all font-mono text-[11px] text-[var(--text-hi)]">{value}</dd></div>; }
function Step({ label, value }: { label: string; value: Date | null }) { return <div className="rounded border border-[var(--border)] bg-[var(--bg)] p-3"><p className="text-[11px] text-[var(--text-mid)]">{label}</p><p className="mt-2 font-mono text-[10px] text-[var(--text-low)]">{value?.toISOString() ?? "not reached"}</p></div>; }
function JsonPanel({ title, value }: { title: string; value: unknown }) { return <Panel title={title}><pre className="max-h-96 overflow-auto whitespace-pre-wrap break-all rounded bg-black/25 p-3 font-mono text-[10px] leading-5 text-[var(--text-mid)]">{JSON.stringify(value, null, 2)}</pre></Panel>; }
function recovery(state: string, digest: string | null) { if (state === "submission_unknown") return digest ? "query chain by stored digest; retry prohibited" : "operator reconciliation required; retry prohibited"; if (state === "evidence_pending" || state === "abort_record_pending") return "automatic reconciliation pending"; if (["confirmed", "blocked", "failed", "expired"].includes(state)) return "terminal"; return "processing"; }
