import Link from "next/link";
import { ArrowRight, ShieldCheck } from "lucide-react";
import { requireWorkspace } from "@/lib/workspace-view.server";
import { workspaceRepository } from "@/lib/control-plane.server";
import { Empty, StatePill, WorkspaceFrame } from "@/components/workspace/WorkspaceFrame";

export const dynamic = "force-dynamic";
export default async function DecisionsPage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ before?: string }> }) {
  const { slug } = await params; const query = await searchParams; const context = await requireWorkspace(slug); const before = decodeCursor(query.before); const result = await workspaceRepository().decisionsForMember({ organizationId: context.organization.id, userId: context.session.user.id, before }); if (!result) return null; const last = result.decisions.at(-1);
  return <WorkspaceFrame slug={slug} name={context.organization.name} eyebrow="Decision ledger" title="Decisions" description="Stable, tenant-scoped history ordered by creation time and intent ID. A protected block is a successful safety outcome, not a transfer failure.">
    {result.decisions.length ? <div className="evidence-surface overflow-hidden rounded-[var(--r-md)]"><div className="hidden grid-cols-[1.2fr_.8fr_.7fr_.7fr_auto] gap-4 border-b border-[var(--divider)] px-4 py-3 font-mono text-[10px] uppercase tracking-[0.1em] text-[var(--text-low)] md:grid"><span>Intent</span><span>Amount</span><span>State</span><span>Evidence</span><span /></div>{result.decisions.map((intent) => <Link key={intent.id} href={`/app/workspaces/${slug}/decisions/${intent.id}`} className="focus-ring grid min-h-20 gap-3 border-b border-[var(--divider)] px-4 py-3 last:border-0 hover:bg-white/[0.025] md:grid-cols-[1.2fr_.8fr_.7fr_.7fr_auto] md:items-center"><span className="min-w-0"><span className="block truncate font-mono text-[12px]">{intent.id}</span><span className="mt-1 block text-[10px] text-[var(--text-low)]">{intent.createdAt.toISOString()}</span></span><span className="font-mono text-[12px] tabular">{intent.amountMist} MIST</span><StatePill value={intent.state} /><span className="flex items-center gap-2 text-[11px] text-[var(--text-mid)]">{intent.state.includes("blocked") ? <ShieldCheck className="h-4 w-4 text-[var(--risk-low)]" /> : null}{intent.evidenceState}</span><ArrowRight className="h-4 w-4 text-[var(--text-low)]" /></Link>)}</div> : <Empty>No spend decisions recorded.</Empty>}
    {result.hasMore && last ? <div className="flex justify-end"><Link className="focus-ring inline-flex min-h-11 items-center rounded border border-[var(--border-hi)] px-4 text-[13px] hover:text-[var(--accent)]" href={`?before=${encodeCursor(last.createdAt, last.id)}`}>Older decisions</Link></div> : null}
  </WorkspaceFrame>;
}
function encodeCursor(createdAt: Date, id: string) { return Buffer.from(JSON.stringify([createdAt.toISOString(), id])).toString("base64url"); }
function decodeCursor(value?: string) { if (!value) return undefined; try { const parsed = JSON.parse(Buffer.from(value, "base64url").toString("utf8")) as unknown; if (!Array.isArray(parsed) || parsed.length !== 2 || typeof parsed[0] !== "string" || typeof parsed[1] !== "string" || !/^[0-9a-f-]{36}$/.test(parsed[1])) return undefined; const createdAt = new Date(parsed[0]); return Number.isNaN(createdAt.getTime()) ? undefined : { createdAt, id: parsed[1] }; } catch { return undefined; } }
