import Link from "next/link";
import { notFound } from "next/navigation";
import { requireWorkspaceOverview } from "@/lib/workspace-view.server";
import { CredentialIssue, StatusAction } from "@/components/workspace/WorkspaceControls";
import { Empty, Panel, StatePill, WorkspaceFrame } from "@/components/workspace/WorkspaceFrame";

export const dynamic = "force-dynamic";
export default async function AgentDetailPage({ params }: { params: Promise<{ slug: string; agentId: string }> }) {
  const { slug, agentId } = await params; const data = await requireWorkspaceOverview(slug); const agent = data.agents.find((x) => x.id === agentId); if (!agent) notFound();
  const assignments = data.assignments.filter((x) => x.agentId === agent.id); const assignmentIds = new Set(assignments.map((x) => x.id)); const decisions = data.decisions.filter((x) => x.agentId === agent.id).slice(0, 10); const counters = data.assignmentCounters.filter((x) => assignmentIds.has(x.assignment.id));
  return <WorkspaceFrame slug={slug} name={data.organization.name} eyebrow="Agent isolation" title={agent.name} description={`External reference ${agent.externalRef}. Identity state, policies, credentials, counters, and decisions remain independently auditable.`}>
    <div className="grid gap-5 lg:grid-cols-[1fr_auto]"><Panel title="Agent state"><div className="flex flex-wrap items-center justify-between gap-3"><StatePill value={agent.status} />{agent.status === "active" ? <StatusAction endpoint={`/api/workspaces/${data.organization.id}/agents/${agent.id}/status`} status="disabled" label="Disable agent" danger /> : <StatusAction endpoint={`/api/workspaces/${data.organization.id}/agents/${agent.id}/status`} status="active" label="Reactivate agent" />}</div></Panel><Panel title="Isolation summary"><p className="font-mono text-2xl tabular">{assignments.length}</p><p className="text-[11px] text-[var(--text-low)]">wallet assignments</p></Panel></div>
    <Panel title="Assignments and credentials">{assignments.length ? <div className="grid gap-4">{assignments.map((assignment) => { const wallet = data.wallets.find((x) => x.id === assignment.walletId); const scope = data.scopes.find((x) => x.assignmentId === assignment.id); const active = data.policyVersions.find((x) => x.version.id === scope?.currentVersionId)?.version; const credentials = data.credentials.filter((x) => x.assignmentId === assignment.id); return <div key={assignment.id} className="rounded-[var(--r-sm)] border border-[var(--border)] bg-[var(--bg)] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{wallet?.label ?? "Unknown wallet"}</h3><p className="mt-1 text-[11px] text-[var(--text-low)]">{active ? `Active policy v${active.version}` : "Policy activation required"}</p></div><StatePill value={assignment.status} /></div><div className="mt-4 flex flex-wrap gap-2">{scope ? <Link href={`/app/workspaces/${slug}/policies/${scope.id}`} className="focus-ring inline-flex min-h-11 items-center rounded border border-[var(--border-hi)] px-3 text-[12px] hover:text-[var(--accent)]">Open policy</Link> : null}{assignment.status === "active" ? <StatusAction endpoint={`/api/workspaces/${data.organization.id}/assignments/${assignment.id}/status`} status="disabled" label="Disable assignment" /> : <StatusAction endpoint={`/api/workspaces/${data.organization.id}/assignments/${assignment.id}/status`} status="active" label="Enable assignment" />}</div><div className="mt-5 border-t border-[var(--divider)] pt-4"><CredentialIssue organizationId={data.organization.id} assignmentId={assignment.id} /><div className="mt-4 grid gap-2">{credentials.map((credential) => <div key={credential.id} className="flex flex-col justify-between gap-2 rounded border border-[var(--border)] px-3 py-2 sm:flex-row sm:items-center"><div><p className="text-[12px]">{credential.name} <span className="font-mono text-[var(--text-low)]">{credential.tokenPrefix}...</span></p><p className="text-[10px] text-[var(--text-low)]">{credential.revokedAt ? `Revoked ${credential.revokedAt.toISOString()}` : credential.expiresAt ? `Expires ${credential.expiresAt.toISOString()}` : "No expiry"}</p></div>{!credential.revokedAt ? <StatusAction endpoint={`/api/workspaces/${data.organization.id}/credentials/${credential.id}/revoke`} method="POST" label="Revoke credential" danger /> : <StatePill value="revoked" />}</div>)}</div></div></div>; })}</div> : <Empty>No wallet assignment exists for this agent.</Empty>}</Panel>
    <Panel title="Isolated budget counters">{counters.length ? <div className="grid gap-3 sm:grid-cols-2">{counters.map(({ counter }) => <div key={`${counter.assignmentId}-${counter.periodKind}-${counter.periodStart.toISOString()}`} className="rounded border border-[var(--border)] bg-[var(--bg)] p-4"><p className="font-mono text-[10px] uppercase text-[var(--text-low)]">{counter.periodKind} / {counter.periodStart.toISOString()}</p><p className="mt-3 font-mono text-[13px]">{counter.spentMist} spent / {counter.reservedMist} reserved MIST</p></div>)}</div> : <Empty>No persisted budget use for this agent.</Empty>}</Panel>
    <Panel title="Recent decisions">{decisions.length ? <div className="divide-y divide-[var(--divider)]">{decisions.map((intent) => <Link key={intent.id} href={`/app/workspaces/${slug}/decisions/${intent.id}`} className="focus-ring flex min-h-14 items-center justify-between gap-4 py-2"><span className="min-w-0"><span className="block truncate font-mono text-[12px]">{intent.id}</span><span className="text-[11px] text-[var(--text-low)]">{intent.amountMist} MIST</span></span><StatePill value={intent.state} /></Link>)}</div> : <Empty>No decisions recorded for this agent.</Empty>}</Panel>
  </WorkspaceFrame>;
}
