import Link from "next/link";
import { notFound } from "next/navigation";
import { requireWorkspaceOverview } from "@/lib/workspace-view.server";
import { workspaceRepository, configuredOrigin } from "@/lib/control-plane.server";
import { agentReadiness } from "@/lib/workspace-model";
import { sui, dateLabel } from "@/lib/workspace-display";
import { CredentialIssue, CreateAssignmentForm, StatusAction } from "@/components/workspace/WorkspaceControls";
import { ActivityList } from "@/components/workspace/ActivityList";
import { Panel, StatePill, WorkspaceFrame } from "@/components/workspace/WorkspaceFrame";
export const dynamic = "force-dynamic";
export default async function Agent({ params }: { params: Promise<{ slug: string; agentId: string }> }) {
  const { slug, agentId } = await params; const data = await requireWorkspaceOverview(slug); const agent = data.agents.find((item) => item.id === agentId); if (!agent) notFound();
  const activity = await workspaceRepository().decisionsForMember({ organizationId: data.organization.id, userId: data.session.user.id, agentId, limit: 10 });
  const assignments = data.assignments.filter((item) => item.agentId === agentId); const readiness = agentReadiness(data, agentId);
  const wallets = data.wallets.filter((wallet) => !assignments.some((item) => item.walletId === wallet.id) && data.scopes.some((scope) => scope.walletId === wallet.id && scope.currentVersionId));
  const origin = process.env.APP_ORIGIN ? configuredOrigin() : "http://localhost:3000";
  return <WorkspaceFrame slug={slug} name={data.organization.name} title={agent.name} description={readiness.detail}>
    <div className="flex flex-wrap items-center justify-between gap-3"><span className={`text-sm font-medium ${readiness.label === "Ready" ? "text-[var(--risk-low)]" : "text-[var(--risk-medium)]"}`}>{readiness.label}</span><StatusAction endpoint={`/api/workspaces/${data.organization.id}/agents/${agent.id}/status`} status={agent.status === "active" ? "disabled" : "active"} label={agent.status === "active" ? "Pause agent" : "Resume agent"} danger={agent.status === "active"} /></div>
    {!assignments.length || wallets.length ? <Panel title="Add wallet access">{wallets.length ? <CreateAssignmentForm organizationId={data.organization.id} wallets={wallets.map(({ id, label }) => ({ id, label }))} agents={[{ id: agent.id, name: agent.name }]} /> : <p className="text-sm">First <Link href={`/app/workspaces/${slug}/wallets`} className="text-[var(--accent)] underline">add a wallet and activate its limits</Link>.</p>}</Panel> : null}
    {assignments.map((assignment) => {
      const wallet = data.wallets.find((item) => item.id === assignment.walletId); const scope = data.scopes.find((item) => item.assignmentId === assignment.id); const policy = data.policyVersions.find(({ version }) => version.id === scope?.currentVersionId)?.version;
      const credentials = data.credentials.filter((item) => item.assignmentId === assignment.id);
      const counters = data.assignmentCounters.filter((item) => item.assignment.id === assignment.id);
      return <Panel key={assignment.id} title={wallet?.label ?? "Wallet access"}>
        <div className="flex flex-wrap items-center gap-3"><StatePill value={assignment.status} />{scope ? <Link className="focus-ring inline-flex min-h-11 items-center rounded border border-[var(--border)] px-3 text-sm text-[var(--accent)]" href={`/app/workspaces/${slug}/policies/${scope.id}`}>{policy ? "Edit agent limits" : "Review and activate limits"}</Link> : null}{policy ? <StatusAction endpoint={`/api/workspaces/${data.organization.id}/assignments/${assignment.id}/status`} status={assignment.status === "active" ? "disabled" : "active"} label={assignment.status === "active" ? "Pause wallet access" : "Enable wallet access"} /> : null}</div>
        {policy ? <div className="my-5 grid gap-3 sm:grid-cols-2">{(["day", "month"] as const).map((period) => { const counter = counters.find((item) => item.counter.periodKind === period)?.counter; const spent = BigInt(counter?.spentMist ?? 0); const reserved = BigInt(counter?.reservedMist ?? 0); const limit = BigInt(period === "day" ? policy.maxPerDayMist : policy.maxPerMonthMist); const available = limit > spent + reserved ? limit - spent - reserved : 0n; return <div key={period} className="rounded border border-[var(--border)] p-4"><p className="text-xs text-[var(--text-low)]">This {period}, UTC</p><p className="mt-2 text-sm">{sui(available)} / {sui(limit)} SUI available</p><p className="mt-2 text-xs text-[var(--text-mid)]">{sui(spent)} spent / {sui(reserved)} pending</p></div>; })}</div> : null}
        <details open={!credentials.some((credential) => !credential.revokedAt)} className="mt-5 border-t border-[var(--divider)] pt-4"><summary className="focus-ring cursor-pointer text-sm font-semibold">Credentials</summary><div className="mt-4 space-y-4"><CredentialIssue organizationId={data.organization.id} assignmentId={assignment.id} />{credentials.map((credential) => <div key={credential.id} className="flex flex-wrap items-center justify-between gap-3 rounded border border-[var(--border)] p-3"><div><p className="text-sm">{credential.name}</p><p className="mt-1 text-xs text-[var(--text-low)]">{credential.revokedAt ? "Revoked" : credential.expiresAt ? `Expires ${dateLabel(credential.expiresAt)}` : "No expiry"} / {credential.lastUsedAt ? `Last request ${dateLabel(credential.lastUsedAt)}` : "Never used"}</p></div>{!credential.revokedAt ? <StatusAction endpoint={`/api/workspaces/${data.organization.id}/credentials/${credential.id}/revoke`} method="POST" label="Revoke" danger /> : null}</div>)}</div></details>
      </Panel>;
    })}
    <Panel title="Connect your agent"><p className="text-sm leading-6 text-[var(--text-mid)]">Use an assignment credential from your local agent or tool. Store it as PRAXIS_TOKEN in your local secret environment. The check below verifies access without making a payment.</p><pre className="mt-4 overflow-auto rounded bg-[var(--bg)] p-4 text-xs leading-6">{`curl --fail --silent --show-error \\\n  -H "Authorization: Bearer $PRAXIS_TOKEN" \\\n  ${origin}/api/v1/agent`}</pre><p className="mt-3 text-sm leading-6 text-[var(--text-mid)]">For Claude Code or Codex, expose this HTTP API through your own local tool or script. A native MCP connector is not included. Payment requests use POST /api/v1/spend-intents and still pass the configured limits.</p><Link className="focus-ring mt-3 inline-flex min-h-11 items-center text-sm text-[var(--accent)]" href="/docs#hosted-agents">Read the hosted agent guide</Link></Panel>
    <Panel title="Recent activity"><ActivityList slug={slug} decisions={activity?.decisions ?? []} agents={[agent]} /></Panel>
    <details className="rounded border border-[var(--border)] p-4"><summary className="focus-ring cursor-pointer text-sm text-[var(--text-low)]">Technical details</summary><p className="mt-3 break-all font-mono text-xs">Agent ID: {agent.id}<br />External reference: {agent.externalRef}</p></details>
  </WorkspaceFrame>;
}
