import { notFound } from "next/navigation";
import { requireWorkspaceOverview } from "@/lib/workspace-view.server";
import { PolicyDraftForm } from "@/components/workspace/WorkspaceControls";
import { Empty, Panel, StatePill, WorkspaceFrame } from "@/components/workspace/WorkspaceFrame";

export const dynamic = "force-dynamic";
export default async function PolicyPage({ params }: { params: Promise<{ slug: string; scopeId: string }> }) {
  const { slug, scopeId } = await params; const data = await requireWorkspaceOverview(slug); const scope = data.scopes.find((x) => x.id === scopeId); if (!scope) notFound();
  const versions = data.policyVersions.filter((x) => x.scope.id === scope.id).map((x) => x.version); const active = versions.find((x) => x.id === scope.currentVersionId); const drafts = versions.filter((x) => x.status === "draft"); const subject = scope.scopeType === "wallet" ? data.wallets.find((x) => x.id === scope.walletId)?.label : data.agents.find((x) => data.assignments.find((a) => a.id === scope.assignmentId)?.agentId === x.id)?.name;
  return <WorkspaceFrame slug={slug} name={data.organization.name} eyebrow={`${scope.scopeType} policy`} title={subject ?? "Policy boundary"} description="Drafts are inert until their exact canonical document and SHA-256 hash are reviewed and activated.">
    {drafts.length ? <div className="rounded-[var(--r-md)] border border-[var(--risk-medium)]/35 bg-[var(--risk-medium-tint)] p-4 text-[13px] text-[var(--risk-medium)]">A saved draft is newer than the active boundary. Existing agent traffic continues to use the active policy until explicit activation.</div> : null}
    <div className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><Panel title="Current boundary" detail={active ? `Activated ${active.activatedAt?.toISOString() ?? ""}` : "No active version"}>{active ? <PolicyDocument policy={active} /> : <Empty>No policy is active. Assignments cannot become executable until activation.</Empty>}</Panel><Panel title="New policy draft" detail="All quantities are integer MIST. The day and month limits must contain the transaction limit."><PolicyDraftForm organizationId={data.organization.id} scopeId={scope.id} /></Panel></div>
    <Panel title="Version history" detail="Append-only policy record. Prior active versions are superseded, never overwritten.">{versions.length ? <div className="grid gap-3">{versions.map((version) => <div key={version.id} className="grid gap-3 rounded border border-[var(--border)] bg-[var(--bg)] p-4 sm:grid-cols-[auto_1fr] sm:items-start"><StatePill value={version.status} /><div className="min-w-0"><div className="flex flex-wrap justify-between gap-2"><span className="font-semibold">Version {version.version}</span><span className="font-mono text-[10px] text-[var(--text-low)]">{version.createdAt.toISOString()}</span></div><p className="mt-2 break-all font-mono text-[10px] text-[var(--text-low)]">{version.policyHash}</p></div></div>)}</div> : <Empty>No policy versions saved.</Empty>}</Panel>
  </WorkspaceFrame>;
}
function PolicyDocument({ policy }: { policy: { version: number; maxPerTxMist: string; maxPerDayMist: string; maxPerMonthMist: string; blockRiskScoreAt: number; requireSimulation: boolean; policyHash: string; canonicalJson: unknown } }) { return <dl className="grid gap-3"><Row label="Version" value={String(policy.version)} /><Row label="Per transaction" value={`${policy.maxPerTxMist} MIST`} /><Row label="Per UTC day" value={`${policy.maxPerDayMist} MIST`} /><Row label="Per UTC month" value={`${policy.maxPerMonthMist} MIST`} /><Row label="Risk block" value={`score >= ${policy.blockRiskScoreAt}`} /><Row label="Simulation" value={policy.requireSimulation ? "required" : "invalid"} /><Row label="Policy hash" value={policy.policyHash} mono /><div className="mt-2"><dt className="mb-2 text-[10px] uppercase text-[var(--text-low)]">Canonical document</dt><dd><pre className="max-h-64 overflow-auto whitespace-pre-wrap break-all rounded bg-black/25 p-3 font-mono text-[10px] text-[var(--text-mid)]">{JSON.stringify(policy.canonicalJson, null, 2)}</pre></dd></div></dl>; }
function Row({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <div className="flex min-w-0 flex-col justify-between gap-1 border-b border-[var(--divider)] pb-2 sm:flex-row"><dt className="text-[11px] text-[var(--text-low)]">{label}</dt><dd className={`${mono ? "break-all font-mono text-[10px]" : "font-mono text-[12px]"}`}>{value}</dd></div>; }
