import { NextResponse } from "next/server";
import { z } from "zod";
import { verifyPersonalMessageSignature } from "@mysten/sui/verify";
import { normalizeSuiAddress } from "@mysten/sui/utils";
import { challengeMessage, createSessionToken, tokenDigest } from "@allen-saji/praxis-control-plane";
import { authRepository, requiredSecret, sha256 } from "@/lib/control-plane.server";
export const dynamic = "force-dynamic";
const schema = z.object({ address: z.string().min(1), nonce: z.string().min(1), signature: z.string().min(1) }).strict();
export async function POST(request: Request) { try { const body = schema.parse(await request.json()); const address = normalizeSuiAddress(body.address); const repo = authRepository(); const nonceHash = sha256(body.nonce); const challenge = await repo.findChallenge(nonceHash, address); if (!challenge || challenge.usedAt || challenge.expiresAt <= new Date()) throw new Error("challenge unavailable"); const uri = process.env.APP_ORIGIN ?? new URL(request.url).origin; const message = challengeMessage({ domain: challenge.domain, uri, address, nonce: body.nonce, issuedAt: challenge.issuedAt, expiresAt: challenge.expiresAt }); await verifyPersonalMessageSignature(new TextEncoder().encode(message), body.signature, { address }); if (!await repo.consumeChallenge(nonceHash, address, new Date())) throw new Error("challenge already used"); const now = new Date(); const sessionToken = createSessionToken(); await repo.createSession({ userId: (await repo.upsertUser(address, now)).id, tokenHash: tokenDigest(sessionToken, requiredPepper()), expiresAt: new Date(now.getTime() + 12 * 60 * 60_000), now }); const response = NextResponse.json({ user: { address } }); response.cookies.set(process.env.NODE_ENV === "production" ? "__Host-praxis_session" : "praxis_session", sessionToken, { httpOnly: true, sameSite: "strict", secure: process.env.NODE_ENV === "production", path: "/", maxAge: 43_200 }); return response; } catch { return NextResponse.json({ error: { code: "AUTHENTICATION_FAILED", message: "Unable to verify login" } }, { status: 401 }); } }
function requiredPepper(): string { return requiredSecret("PRAXIS_SESSION_PEPPER"); }
